language: node_js
node_js: 6

jobs:
  include:
    - stage: install
      cache: yarn
      script: ./scripts/install.sh
    - stage: test
      script: ./scripts/test.sh
    - stage: deploy
      if: branch = master
      node_js: 6
      script: ./scripts/deploy.sh
