service:
  name: userapi-sls-ts

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs6.10
  profile: default
  region: ap-northeast-2

functions:
  create:
    handler: src/handler.create
    events:
      - http:
          method: post
          path: users/create
  
  retrieve:
    handler: src/handler.retrieve
    events:
      - http:
          method: post
          path: users/
  
  retrieveAll:
    handler: src/handler.retrieveAll
    events:
      - http:
          method: get
          path: users/
  
  update:
    handler: src/handler.update
    events:
      - http:
          method: put
          path: users/update
  
  remove:
    handler: src/handler.remove
    events:
      - http:
          method: delete
          path: users/delete
  resources:
    Resources:
      UsersTable:
        Type: AWS::DynamoDB::Table	
        Properties:	
          TableName: sample-userdb	
          AttributeDefinitions:	
            - AttributeName: uuid	
              AttributeType: S	
            - AttributeName: username	
              AttributeType: S	
          KeySchema:	
            - AttributeName: uuid	
              KeyType: HASH	
            - AttributeName: username	
              KeyType: RANGE	
          ProvisionedThroughput:	
            ReadCapacityUnits: 5	
            WriteCapacityUnits: 5 