service:
  name: sls-ts-sample

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs6.10

functions:
  create:
    handler: src/handler.create
    events:
      - http:
          method: post
          path: users/create
